document.writeln("<div class=\'hide\'>");
document.writeln("						<div class=\'column_navigation\'>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/index.html\' target=\'_blank\' title=\'网站首页\'>网站首页</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/index.html#zxbd\' target=\'_blank\' title=\'最新报道\'>最新报道</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/index.html#zwgk\' target=\'_blank\' title=\'政务公开\'>政务公开</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/ldzc/index.html\' target=\'_blank\' title=\'领导之窗\'>领导之窗</a> </div>");
document.writeln("							</div>");
document.writeln("                            <div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'>  <a href=\'404.html\' target=\'_blank\' title=\'直播平台\'>直播平台</a></div>");
document.writeln("							</div>");
document.writeln("                            <div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../Training_Platform/index.html\' target=\'_blank\' title=\'代练平台\'>代练平台</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/Ancillary_page/gybw.html\' target=\'_blank\' title=\'关于本网\'>关于本网</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'../../home/Ancillary_page/wzsm.html\' target=\'_blank\' title=\'网站声明\'>网站声明</a> </div>");
document.writeln("								");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'clear\'></div>");