document.writeln("<div class=\'hide\'>");
document.writeln("						<div class=\'column_navigation\'>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/index/index.html\' target=\'_blank\' title=\'官网主页\'>官网主页</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/index/index.html#zxbd\' target=\'_blank\' title=\'最新报道\'>最新报道</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/404.html\' target=\'_blank\' title=\'政务公开\'>政务公开</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/index/data/ldzc/xxnmq.html\' target=\'_blank\' title=\'队长简历\'>队长简历</a> </div>");
document.writeln("							</div>");
document.writeln("                            <div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'>  <a href=\'https://hddj.vercel.app/404.html\' target=\'_blank\' title=\'直播平台\'>直播平台</a></div>");
document.writeln("							</div>");
document.writeln("                            <div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/Training_Platform/index.html\' target=\'_blank\' title=\'代练平台\'>代练平台</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/index/data/Ancillary_page/gybw.html\' target=\'_blank\' title=\'关于本网\'>关于本网</a> </div>");
document.writeln("							</div>");
document.writeln("							<div class=\'navigation_bar\'>");
document.writeln("								<div class=\'navbar\'> <a href=\'https://hddj.vercel.app/index/data/Ancillary_page/gybw.html\' target=\'_blank\' title=\'网站声明\'>网站声明</a> </div>");
document.writeln("								");
document.writeln("							</div>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					<div class=\'clear\'></div>");